// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blazor_test.Data;

#nullable disable

namespace blazortest.Migrations
{
    [DbContext(typeof(ConnectionDbContext))]
    [Migration("20231224171943_AccessKeyV2")]
    partial class AccessKeyV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("blazor_test.Models.AccessKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revoked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("blazor_test.Models.Labeling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhraseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhraseId");

                    b.ToTable("Labelings");
                });

            modelBuilder.Entity("blazor_test.Models.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("blazor_test.Models.Labeling", b =>
                {
                    b.HasOne("blazor_test.Models.Phrase", "Phrase")
                        .WithMany("Labelings")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("blazor_test.Models.Phrase", b =>
                {
                    b.Navigation("Labelings");
                });
#pragma warning restore 612, 618
        }
    }
}
